"""Export the QuickBricks collection and pages from existing model outputs.

Run `.venv/bin/python tools/quick_site.py` after building a model. This exports
viewer geometry and copies existing assets; it never renders images or videos.
The catalog includes every model.toml with model.collection = "quick_bricks",
including models with no video, poster, or instruction PDF yet.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import shutil
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COLLECTION = "quick_bricks"
ORIGIN = "https://bricks.superfun.games"
GENERATED = "<!-- generated by tools/quick_site.py from quick-model.html: edit the template, not this file -->"


def quick_projects(models_dir: Path) -> list[Path]:
    return [p.parent for p in sorted(models_dir.glob("*/model.toml"))
            if not p.parent.name.startswith("_")
            and tomllib.loads(p.read_text()).get("model", {}).get("collection") == COLLECTION]


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


def _hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()[:12]


def _asset_url(site: Path, path: Path) -> str | None:
    if not path.is_file():
        return None
    return f"/{path.relative_to(site).as_posix()}?v={_hash(path)}"


def _copy(src: Path, dst: Path) -> None:
    if src.is_file() and (not dst.exists() or _hash(src) != _hash(dst)):
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def quick_page(template: str, item: dict) -> str:
    """Fill the same meta/data-fill markers as the main model-page template."""
    name = html.escape(item["name"], quote=False)
    desc = html.escape(item["description"], quote=True)
    title = f"{name} | Quick Bricks"
    url = ORIGIN + item["url"]
    tags = [f"<title>{title}</title>",
            f'<meta name="description" content="{desc}">',
            f'<link rel="canonical" href="{url}">',
            '<meta property="og:type" content="website">',
            f'<meta property="og:title" content="{html.escape(item["name"], quote=True)} | Quick Bricks">',
            f'<meta property="og:description" content="{desc}">',
            f'<meta property="og:url" content="{url}">',
            '<meta name="twitter:card" content="summary_large_image">']
    if item["poster"]:
        tags.append(f'<meta property="og:image" content="{ORIGIN}{item["poster"]}">')
    page = re.sub(r"<!-- meta:start -->.*?<!-- meta:end -->",
                  lambda _: "<!-- meta:start -->\n" + "\n".join(tags) + "\n<!-- meta:end -->",
                  template, count=1, flags=re.S)
    page = page.replace('data-slug=""', f'data-slug="{html.escape(item["slug"], quote=True)}"', 1)
    for key in ("name", "description"):
        page = re.sub(r'(<[^>]*data-fill="' + key + r'"[^>]*>)[^<]*(<)',
                      lambda m: m[1] + html.escape(item[key], quote=False) + m[2], page)
    return page.replace("<!doctype html>", "<!doctype html>\n" + GENERATED, 1)


def build_quick_site(site: Path = ROOT / "site", models_dir: Path = ROOT / "models") -> dict:
    """Index already-exported QuickBricks, sync existing videos, and generate pages.

    Missing exports fail explicitly so adding a model cannot silently omit it.
    Existing site videos remain usable if the local output has been archived.
    """
    items = []
    for project in quick_projects(models_dir):
        slug = project.name
        cfg = tomllib.loads((project / "model.toml").read_text())["model"]
        model_dir = site / "models" / slug
        model_path = model_dir / "model.json"
        if not model_path.exists():
            raise FileNotFoundError(f"QuickBricks export missing for {slug}; run tools/quick_site.py first")
        data = json.loads(model_path.read_text())
        if data.get("collection") != COLLECTION:
            raise ValueError(f"QuickBricks export for {slug} is stale; run tools/quick_site.py first")
        files = data.get("files", {})
        video = site / "quick" / f"{slug}-1080x1920.mp4"
        _copy(project / "out" / video.name, video)
        posters = [model_dir / files[k] for k in ("quick_poster", "video_poster") if files.get(k)]
        posters += [model_dir / r for r in files.get("renders", [])]
        poster = next((p for p in posters if p.is_file()), None)
        booklet = model_dir / files["booklet"] if files.get("booklet") else None
        items.append({
            "slug": slug, "name": data["name"], "description": cfg.get("description", ""),
            "collection": COLLECTION, "pieces": data.get("pieces", data["parts"]),
            "steps": len(data.get("steps", [])), "video": _asset_url(site, video),
            "poster": _asset_url(site, poster) if poster else None,
            "instructions": _asset_url(site, booklet) if booklet else None,
            "url": f"/quick/{slug}/", "model": _asset_url(site, model_path),
            "geometry": _asset_url(site, model_dir / files.get("glb", "model.glb")),
        })
    result = {"models": items}
    _write(site / "quick" / "models.json", json.dumps(result, indent=2, ensure_ascii=False) + "\n")
    template_path = site / "quick-model.html"
    if template_path.exists():
        template = template_path.read_text()
        for item in items:
            _write(site / "quick" / item["slug"] / "index.html", quick_page(template, item))
        live = {m["slug"] for m in items}
        for page in (site / "quick").glob("*/index.html"):
            if page.parent.name not in live and GENERATED in page.read_text():
                page.unlink()
    return result


def export_quick_models(engine, site: Path, models_dir: Path) -> None:
    from brickkit.project import Project
    from brickkit.viewer_export import export_model
    for folder in quick_projects(models_dir):
        project = Project(folder.name, models_dir)
        export_model(engine, project, project.build(engine.catalog), site)
        print(f"  exported {project.slug}", flush=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", type=Path, default=ROOT / "site")
    parser.add_argument("--models", type=Path, default=ROOT / "models")
    parser.add_argument("--index-only", action="store_true", help="Use already-exported viewer data")
    args = parser.parse_args()
    if not args.index_only:
        sys.path.insert(0, str(ROOT))
        from brickkit.engine import Engine
        export_quick_models(Engine(), args.site, args.models)
    index = build_quick_site(args.site, args.models)
    print(f"QuickBricks: {len(index['models'])} models, "
          f"{sum(m['video'] is not None for m in index['models'])} videos")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
