"""Generate the static site's derived assets from the brickkit exports in site/.

Run after exporting models (`python -m brickkit viewer <slug>`):

    .venv/bin/python tools/site_assets.py

Writes (all inside site/):
  favicon.svg, favicon.ico (16/32/48), favicon-32.png, apple-touch-icon.png, icon-192.png,
  icon-512.png, icon-maskable-192.png, icon-maskable-512.png, site.webmanifest
  assets/brand/logo-header.{png,webp}, assets/brand/logo-square.png
  assets/og/home.png and assets/og/<slug>.png          1200x630 link-preview images
  assets/img/<slug>/<render>{,-480}.webp               web-sized copies of the renders
  assets/media.json                                    content hashes + sizes (cache busting)
  m/<slug>/index.html                                  per-model page with its own meta tags
  sitemap.xml
and stamps ?v=<hash> onto image/icon URLs in index.html, model.html and 404.html.

Only Pillow is needed. It is safe to re-run; stale generated pages and images for models that
are no longer in models.json are removed.
"""
from __future__ import annotations

import hashlib
import html
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
ORIGIN = "https://lego.superfun.games"
SITE_NAME = "L'Eggo my LEGO"
SHORT_NAME = "L'Eggo"
SITE_DESC = ("Buildable models made from real LEGO parts. Every part, connection and step "
             "checked by computer.")
GENERATED = "<!-- generated by tools/site_assets.py from model.html: edit model.html, not this file -->"

YELLOW = (254, 219, 5)
RED = (235, 21, 44)
BLACK = (17, 16, 16)
WHITE = (255, 255, 255)
BG_LIGHT = "#f7f7f2"
THEME = "#f7f7f2"

LOGO_SRC = ROOT / "logo.png" if (ROOT / "logo.png").exists() else SITE / "assets" / "logo.png"
FONT = SITE / "assets" / "fonts" / "Fredoka.ttf"
LOGO_CROP = (28, 174, 1218, 1066)          # the logo's lettering, 4:3, inside the 1254 px square


# ---------------------------------------------------------------- helpers

def sha(path: Path, n: int = 10) -> str:
    return hashlib.sha1(path.read_bytes()).hexdigest()[:n]


def font(size: int, weight: int = 700) -> ImageFont.FreeTypeFont:
    f = ImageFont.truetype(str(FONT), size)
    try:
        f.set_variation_by_axes([weight, 100])
    except Exception:
        pass
    return f


def fmt_cm(mm: float) -> str:
    cm = mm / 10
    return f"{cm:.0f}" if cm >= 100 else f"{cm:.1f}".removesuffix(".0")


def lede(d: dict) -> str:
    """Same wording as ledeFor() in assets/js/model.js."""
    if d.get("description"):
        return d["description"]
    s = f"{d.get('pieces', d['parts']):,} real LEGO parts, about {fmt_cm((d.get('dims_mm') or [0, 0, 0])[1])} cm tall"
    extras = []
    if d.get("mechanism"):
        extras.append("a working mechanism")
    if d.get("lights"):
        extras.append("a built-in light" if len(d["lights"]) == 1 else "built-in lights")
    if extras:
        s += ", with " + " and ".join(extras)
    return s + ". Every part, connection and step checked by computer."


def best_render(renders: list[str]) -> str | None:
    for pat in (r"hero", r"three.?quarter"):
        for r in renders:
            if re.search(pat, r, re.I):
                return r
    return renders[0] if renders else None


def write_if_changed(path: Path, data: bytes | str) -> None:
    b = data.encode() if isinstance(data, str) else data
    if path.exists() and path.read_bytes() == b:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b)


def save_png(img: Image.Image, path: Path, **kw) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path, "PNG", optimize=True, **kw)


def rounded_mask(size: tuple[int, int], radius: int, scale: int = 4) -> Image.Image:
    w, h = size
    m = Image.new("L", (w * scale, h * scale), 0)
    ImageDraw.Draw(m).rounded_rectangle((0, 0, w * scale - 1, h * scale - 1), radius * scale, fill=255)
    return m.resize(size, Image.LANCZOS)


def studs_background(w: int, h: int, pitch: int = 42, r: int = 12) -> Image.Image:
    """Brand yellow with a soft LEGO stud grid (shadow ring + highlight)."""
    s = 2
    img = Image.new("RGB", (w * s, h * s), YELLOW)
    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    P, R = pitch * s, r * s
    for y in range(-P // 2, h * s + P, P):
        for x in range(-P // 2, w * s + P, P):
            d.ellipse((x - R + 3, y - R + 4, x + R + 3, y + R + 4), fill=(140, 95, 0, 34))
            d.ellipse((x - R, y - R, x + R, y + R), fill=(255, 236, 110, 150))
            d.ellipse((x - R + 5, y - R + 5, x + R - 5, y + R - 5), fill=(255, 226, 40, 120))
    img.paste(layer, (0, 0), layer)
    return img.resize((w, h), Image.LANCZOS)


def card(img: Image.Image, radius: int, border: int = 6, shadow: tuple[int, int] = (14, 16)) -> Image.Image:
    """Image in a rounded card with a black outline and a hard offset shadow (the site's sticker look)."""
    w, h = img.size
    W, H = w + border * 2 + shadow[0], h + border * 2 + shadow[1]
    out = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    black = Image.new("RGBA", (w + border * 2, h + border * 2), BLACK + (255,))
    m = rounded_mask(black.size, radius + border)
    out.paste(black, shadow, m)
    out.paste(black, (0, 0), m)
    out.paste(img.convert("RGBA"), (border, border), rounded_mask((w, h), radius))
    return out


def wrap(text: str, f: ImageFont.FreeTypeFont, width: int) -> list[str]:
    words, lines, cur = text.split(), [], ""
    for w in words:
        t = f"{cur} {w}".strip()
        if f.getlength(t) <= width or not cur:
            cur = t
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def pill(draw: ImageDraw.ImageDraw, xy: tuple[int, int], text: str, f, fg, bg, pad=(22, 12)) -> int:
    x, y = xy
    l, t, r, b = f.getbbox(text)
    w, h = r - l + pad[0] * 2, f.size + pad[1] * 2
    draw.rounded_rectangle((x, y, x + w, y + h), h // 2, fill=bg)
    draw.text((x + pad[0], y + h / 2), text, font=f, fill=fg, anchor="lm")
    return w


# ---------------------------------------------------------------- brand + icons

MARK_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
<rect width="64" height="64" rx="14" fill="#fedb05"/>
<rect x="10" y="10" width="44" height="44" rx="9" fill="#eb152c" stroke="#111010" stroke-width="4"/>
<g fill="#ff5a68" stroke="#b80d1f" stroke-width="1.6">
<circle cx="24" cy="24" r="6.2"/><circle cx="40" cy="24" r="6.2"/><circle cx="24" cy="40" r="6.2"/><circle cx="40" cy="40" r="6.2"/>
</g>
<g fill="#fff" fill-opacity=".8">
<circle cx="22" cy="22" r="1.8"/><circle cx="38" cy="22" r="1.8"/><circle cx="22" cy="38" r="1.8"/><circle cx="38" cy="38" r="1.8"/>
</g>
</svg>
"""


def draw_mark(size: int, rounded: bool = True) -> Image.Image:
    """Raster version of MARK_SVG (drawn at 16x and downsampled). Tiny sizes skip the highlights."""
    S = 16
    k = size * S / 64
    img = Image.new("RGBA", (size * S, size * S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    if rounded:
        d.rounded_rectangle((0, 0, size * S - 1, size * S - 1), 14 * k, fill=YELLOW)
    else:
        d.rectangle((0, 0, size * S, size * S), fill=YELLOW)
    sw = 4 * k
    d.rounded_rectangle((10 * k - sw / 2, 10 * k - sw / 2, 54 * k + sw / 2, 54 * k + sw / 2), 9 * k + sw / 2, fill=BLACK)
    d.rounded_rectangle((10 * k + sw / 2, 10 * k + sw / 2, 54 * k - sw / 2, 54 * k - sw / 2), 9 * k - sw / 2, fill=RED)
    for cx, cy in ((24, 24), (40, 24), (24, 40), (40, 40)):
        r, s2 = 6.2 * k, 1.6 * k
        if size >= 24:
            d.ellipse((cx * k - r - s2 / 2, cy * k - r - s2 / 2, cx * k + r + s2 / 2, cy * k + r + s2 / 2), fill=(184, 13, 31))
            d.ellipse((cx * k - r + s2 / 2, cy * k - r + s2 / 2, cx * k + r - s2 / 2, cy * k + r - s2 / 2), fill=(255, 90, 104))
            h = 1.8 * k
            d.ellipse(((cx - 2) * k - h, (cy - 2) * k - h, (cx - 2) * k + h, (cy - 2) * k + h), fill=(255, 255, 255, 204))
        else:
            d.ellipse((cx * k - r, cy * k - r, cx * k + r, cy * k + r), fill=(255, 120, 130))
    return img.resize((size, size), Image.LANCZOS)


def logo_square(size: int, content: float = 1.0) -> Image.Image:
    """The logo on its yellow square; content < 1 shrinks the lettering (maskable safe zone)."""
    src = Image.open(LOGO_SRC).convert("RGB")
    crop = src.crop((47, 47, 1207, 1207))                 # trim the empty margin a little
    if content >= 1:
        return crop.resize((size, size), Image.LANCZOS)
    out = Image.new("RGB", (size, size), YELLOW)
    inner = crop.resize((round(size * content), round(size * content)), Image.LANCZOS)
    off = (size - inner.width) // 2
    out.paste(inner, (off, off))
    return out


def logo_lettering() -> Image.Image:
    return Image.open(LOGO_SRC).convert("RGB").crop(LOGO_CROP)


def build_brand() -> None:
    brand = SITE / "assets" / "brand"
    brand.mkdir(parents=True, exist_ok=True)
    if LOGO_SRC != SITE / "assets" / "logo.png":
        write_if_changed(SITE / "assets" / "logo.png", LOGO_SRC.read_bytes())
    lt = logo_lettering()
    hdr = lt.resize((128, 96), Image.LANCZOS)
    save_png(hdr, brand / "logo-header.png")
    hdr.save(brand / "logo-header.webp", "WEBP", quality=90, method=6)
    save_png(logo_square(600), brand / "logo-square.png")

    write_if_changed(SITE / "favicon.svg", MARK_SVG)
    sizes = [16, 32, 48]
    ico = [draw_mark(s) for s in sizes]
    ico[-1].save(SITE / "favicon.ico", format="ICO", sizes=[(s, s) for s in sizes], append_images=ico[:-1])
    save_png(draw_mark(32), SITE / "favicon-32.png")
    save_png(logo_square(180), SITE / "apple-touch-icon.png")
    save_png(logo_square(192), SITE / "icon-192.png")
    save_png(logo_square(512), SITE / "icon-512.png")
    save_png(logo_square(192, 0.72), SITE / "icon-maskable-192.png")
    save_png(logo_square(512, 0.72), SITE / "icon-maskable-512.png")


def build_manifest() -> None:
    v = lambda name: f"/{name}?v={sha(SITE / name)}"          # noqa: E731
    manifest = {
        "name": SITE_NAME,
        "short_name": SHORT_NAME,
        "description": SITE_DESC,
        "id": "/",
        "start_url": "/",
        "scope": "/",
        "display": "standalone",
        "background_color": BG_LIGHT,
        "theme_color": THEME,
        "icons": [
            {"src": v("icon-192.png"), "sizes": "192x192", "type": "image/png", "purpose": "any"},
            {"src": v("icon-512.png"), "sizes": "512x512", "type": "image/png", "purpose": "any"},
            {"src": v("icon-maskable-192.png"), "sizes": "192x192", "type": "image/png", "purpose": "maskable"},
            {"src": v("icon-maskable-512.png"), "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
            {"src": v("favicon.svg"), "sizes": "any", "type": "image/svg+xml", "purpose": "any"},
        ],
    }
    write_if_changed(SITE / "site.webmanifest", json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------- OG images

def og_home() -> None:
    W, H = 1200, 630
    img = studs_background(W, H)
    lt = logo_lettering().resize((440, 330), Image.LANCZOS)
    c = card(lt, 28, border=6, shadow=(12, 14)).rotate(3, resample=Image.BICUBIC, expand=True)
    img.paste(c, (50, (H - c.height) // 2 - 4), c)
    d = ImageDraw.Draw(img)
    x, width = 580, 570
    lines = (("Real LEGO models,", BLACK), ("checked by computer.", RED))
    size = 72
    while size > 40 and max(font(size, 700).getlength(t) for t, _ in lines) > width:
        size -= 2
    f1 = font(size, 700)
    y = 150
    for line, col in lines:
        d.text((x, y), line, font=f1, fill=col)
        y += int(size * 1.12)
    f2 = font(28, 500)
    y += 26
    for line in wrap("Every part a real LEGO element. Every connection found. No collisions. Every step buildable.", f2, width):
        d.text((x, y), line, font=f2, fill=(40, 34, 10))
        y += 38
    f3 = font(26, 600)
    pill(d, (x, H - 104), "lego.superfun.games", f3, WHITE, BLACK)
    out = SITE / "assets" / "og" / "home.png"
    save_png(img.convert("RGB"), out)


def crop_to_subject(pic: Image.Image, pad: float = 0.1) -> Image.Image:
    """Square crop around whatever differs from the studio background (estimated per row from
    the left and right edges), so the model fills the frame."""
    import numpy as np
    a = np.asarray(pic.convert("RGB")).astype(np.int16)
    edge = np.concatenate([a[:, :12], a[:, -12:]], axis=1)
    bg = np.median(edge, axis=1)[:, None, :]
    mask = np.abs(a - bg).sum(axis=2) > 36
    ys, xs = np.nonzero(mask)
    if len(xs) < 50:
        side = min(pic.size)
        return pic.crop(((pic.width - side) // 2, (pic.height - side) // 2, (pic.width + side) // 2, (pic.height + side) // 2))
    x0, x1, y0, y1 = xs.min(), xs.max(), ys.min(), ys.max()
    side = int(max(x1 - x0, y1 - y0) * (1 + 2 * pad))
    side = min(side, min(pic.size))
    cx, cy = (x0 + x1) // 2, (y0 + y1) // 2
    left = min(max(0, cx - side // 2), pic.width - side)
    top = min(max(0, cy - side // 2), pic.height - side)
    return pic.crop((left, top, left + side, top + side))


def og_model(m: dict, data: dict, slug_dir: Path) -> Path | None:
    W, H = 1200, 630
    img = studs_background(W, H)
    renders = data.get("files", {}).get("renders") or []
    r = best_render(renders)
    if r and (slug_dir / r).exists():
        pic = crop_to_subject(Image.open(slug_dir / r).convert("RGB"))
        pic = pic.resize((500, 500), Image.LANCZOS)
        c = card(pic, 36, border=6, shadow=(14, 16)).rotate(-2.5, resample=Image.BICUBIC, expand=True)
        img.paste(c, (W - c.width - 40, (H - c.height) // 2), c)
    d = ImageDraw.Draw(img)
    x = 64
    logo = logo_lettering().resize((132, 99), Image.LANCZOS)
    lc = card(logo, 14, border=4, shadow=(5, 6)).rotate(-3, resample=Image.BICUBIC, expand=True)
    img.paste(lc, (x - 6, 34), lc)
    name = data.get("name") or m.get("name") or m["slug"]
    size = 92
    while size > 48:
        f1 = font(size, 700)
        lines = wrap(name, f1, 510)
        if len(lines) <= 2 and all(f1.getlength(line) <= 510 for line in lines):
            break
        size -= 6
    y = 206 if len(lines) == 1 else 176
    for line in lines:
        d.text((x, y), line, font=f1, fill=BLACK)
        y += int(size * 1.02)
    y += 22
    f2 = font(32, 600)
    w = pill(d, (x, y), f"{data.get('pieces', data['parts']):,} real LEGO parts", f2, WHITE, RED)
    h_cm = fmt_cm((data.get("dims_mm") or [0, 0, 0])[1])
    f3 = font(28, 500)
    d.text((x, y + 82), f"{h_cm} cm tall · checked by computer", font=f3, fill=(40, 34, 10))
    f4 = font(24, 600)
    pill(d, (x, H - 78), "lego.superfun.games", f4, WHITE, BLACK, pad=(18, 10))
    out = SITE / "assets" / "og" / f"{m['slug']}.png"
    save_png(img.convert("RGB"), out)
    return out


# ---------------------------------------------------------------- per-model media

def model_media(slug: str, data: dict, slug_dir: Path) -> dict:
    files = {}
    for p in sorted(slug_dir.rglob("*")):
        if p.is_file() and not p.name.startswith("."):
            files[p.relative_to(slug_dir).as_posix()] = {"v": sha(p), "size": p.stat().st_size}
    images = {}
    out_dir = SITE / "assets" / "img" / slug
    wanted = set()
    for r in data.get("files", {}).get("renders") or []:
        src = slug_dir / r
        if not src.exists():
            continue
        im = Image.open(src)
        im = im.convert("RGBA") if im.mode in ("RGBA", "LA", "P") else im.convert("RGB")
        stem = Path(r).stem
        lg, sm = out_dir / f"{stem}.webp", out_dir / f"{stem}-480.webp"
        out_dir.mkdir(parents=True, exist_ok=True)
        key = files.get(r, {}).get("v", "")
        stamp = out_dir / f".{stem}.src"
        if not (lg.exists() and sm.exists() and stamp.exists() and stamp.read_text() == key):
            im.save(lg, "WEBP", quality=84, method=6)
            small = im.resize((480, round(480 * im.height / im.width)), Image.LANCZOS) if im.width > 480 else im
            small.save(sm, "WEBP", quality=82, method=6)
            stamp.write_text(key)
        wanted |= {lg.name, sm.name, stamp.name}
        images[r] = {"w": im.width, "h": im.height,
                     "lg": f"/assets/img/{slug}/{lg.name}?v={sha(lg)}",
                     "sm": f"/assets/img/{slug}/{sm.name}?v={sha(sm)}"}
    if out_dir.exists():
        for p in out_dir.iterdir():
            if p.name not in wanted:
                p.unlink()
    return {"files": files, "images": images}


# ---------------------------------------------------------------- pages

def attr(s: str) -> str:
    return html.escape(s, quote=False).replace('"', "&quot;")


def model_meta(m: dict, data: dict, og_v: str) -> str:
    slug = m["slug"]
    name = data.get("name") or m.get("name") or slug
    title = f"{name}: buildable LEGO model | {SITE_NAME}"
    og_title = f"{name}: buildable LEGO model"
    desc = lede(data)
    url = f"{ORIGIN}/m/{slug}/"
    og = f"{ORIGIN}/assets/og/{slug}.png?v={og_v}"
    ld = {
        "@context": "https://schema.org",
        "@type": "CreativeWork",
        "name": name,
        "description": desc,
        "url": url,
        "image": og,
        "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": ORIGIN + "/"},
        "keywords": "LEGO, MOC, building instructions, parts list, " + name,
    }
    return "\n".join([
        f"<title>{html.escape(title, quote=False)}</title>",
        f'<meta name="description" content="{attr(desc)}">',
        f'<link rel="canonical" href="{attr(url)}">',
        f'<meta property="og:site_name" content="{attr(SITE_NAME)}">',
        '<meta property="og:type" content="website">',
        f'<meta property="og:title" content="{attr(og_title)}">',
        f'<meta property="og:description" content="{attr(desc)}">',
        f'<meta property="og:url" content="{attr(url)}">',
        f'<meta property="og:image" content="{attr(og)}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{attr(f"{name}, a model built from {data.get("pieces", data["parts"]):,} real LEGO parts")}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{attr(og_title)}">',
        f'<meta name="twitter:description" content="{attr(desc)}">',
        f'<meta name="twitter:image" content="{attr(og)}">',
        f'<script type="application/ld+json">{json.dumps(ld, ensure_ascii=False)}</script>',
    ])


def model_page(template: str, m: dict, data: dict, og_v: str, notice: str) -> str:
    slug = m["slug"]
    name = data.get("name") or slug
    page = re.sub(r"<!-- meta:start -->.*?<!-- meta:end -->",
                  lambda _: "<!-- meta:start -->\n" + model_meta(m, data, og_v) + "\n<!-- meta:end -->",
                  template, count=1, flags=re.S)
    page = page.replace('data-slug=""', f'data-slug="{attr(slug)}"', 1)
    page = re.sub(r'(<[^>]*data-fill="name"[^>]*>)[^<]*(<)', lambda mm: mm.group(1) + html.escape(name, quote=False) + mm.group(2), page)
    page = re.sub(r'(<[^>]*data-fill="description"[^>]*>)[^<]*(<)', lambda mm: mm.group(1) + html.escape(lede(data), quote=False) + mm.group(2), page)
    if notice:
        page = page.replace('<span id="model-notices"></span>', f'<span id="model-notices">{html.escape(notice, quote=False)}</span>', 1)
    return page.replace("<!doctype html>", "<!doctype html>\n" + GENERATED, 1)


STAMP_RE = re.compile(r'((?:href|src|srcset|content)=")((?:https://lego\.superfun\.games)?/(?!vendor/)[^"?#\s]+\.(?:png|webp|ico|svg|webmanifest|jpg))(?:\?v=[0-9a-f]+)?(")')


def stamp(text: str) -> str:
    """Add ?v=<content hash> to local image/icon URLs so they can be cached for a long time."""
    def rep(mm):
        url = mm.group(2)
        path = SITE / url.split(ORIGIN, 1)[-1].lstrip("/")
        if not path.is_file():
            return mm.group(0)
        return f"{mm.group(1)}{url}?v={sha(path)}{mm.group(3)}"
    return STAMP_RE.sub(rep, text)


def sitemap(entries: list[tuple[str, str]]) -> str:
    rows = "\n".join(f"  <url><loc>{html.escape(u)}</loc><lastmod>{d}</lastmod></url>" for u, d in entries)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + rows + "\n</urlset>\n")


def day(path: Path) -> str:
    return datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).strftime("%Y-%m-%d")


# ---------------------------------------------------------------- main

def main() -> int:
    index_path = SITE / "models.json"
    if not index_path.exists():
        print("site/models.json not found: export a model first (python -m brickkit viewer <slug>)", file=sys.stderr)
        return 1
    models = json.loads(index_path.read_text()).get("models", [])
    conf_path = SITE / "site.json"
    conf = json.loads(conf_path.read_text()) if conf_path.exists() else {}
    notices = conf.get("notices", {})

    build_brand()
    build_manifest()
    og_home()

    template = (SITE / "model.html").read_text()
    media = {"models": {}}
    slugs = []
    entries = []
    for m in models:
        slug = m["slug"]
        slug_dir = SITE / "models" / slug
        mj = slug_dir / "model.json"
        if not mj.exists():
            print(f"  skip {slug}: {mj} missing", file=sys.stderr)
            continue
        data = json.loads(mj.read_text())
        slugs.append(slug)
        media["models"][slug] = model_media(slug, data, slug_dir)
        og = og_model(m, data, slug_dir)
        notice = data.get("notice") or data.get("credits") or notices.get(slug, "")
        page = model_page(template, m, data, sha(og), notice)
        write_if_changed(SITE / "m" / slug / "index.html", stamp(page))
        entries.append((f"{ORIGIN}/m/{slug}/", day(mj)))
        print(f"  {slug}: page, og image, {len(media['models'][slug]['images'])} web images")

    # clean up generated output for models that are gone
    for d in (SITE / "m").glob("*/"):
        if d.name not in slugs and (d / "index.html").exists() and GENERATED in (d / "index.html").read_text():
            shutil.rmtree(d)
    for p in (SITE / "assets" / "og").glob("*.png"):
        if p.stem != "home" and p.stem not in slugs:
            p.unlink()
    for d in (SITE / "assets" / "img").glob("*/"):
        if d.name not in slugs:
            shutil.rmtree(d)

    write_if_changed(SITE / "assets" / "media.json", json.dumps(media, indent=1) + "\n")
    home_day = max([day(SITE / "index.html")] + [e[1] for e in entries])
    extra = [(f"{ORIGIN}/videos/", max(home_day, day(SITE / "videos" / "index.html")))] \
        if (SITE / "videos" / "index.html").exists() else []
    write_if_changed(SITE / "sitemap.xml", sitemap([(f"{ORIGIN}/", home_day)] + extra + entries))

    for name in ("index.html", "model.html", "404.html", "videos/index.html"):
        p = SITE / name
        if p.exists():
            write_if_changed(p, stamp(p.read_text()))
    print(f"site assets written for {len(slugs)} model(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
