"""Generate the static site's derived assets from the brickkit exports in site/.

Run after exporting models (`python -m brickkit viewer <slug>`):

    .venv/bin/python tools/site_assets.py

Writes inside site/:
  favicon.svg, favicon.ico (16/32/48), favicon-32.png, apple-touch-icon.png, icon-192.png,
  icon-512.png, icon-maskable-192.png, icon-maskable-512.png, site.webmanifest
  assets/brand/logo-header.{png,webp}, assets/brand/logo-square.png
  assets/logo.png (also copied to ROOT/logo.png for booklet/video exporters)
  assets/og/home.png and assets/og/<slug>.png          1200x630 link-preview images
  assets/img/<slug>/<render>{,-480}.webp               web-sized copies of the renders
  assets/media.json                                    content hashes + sizes (cache busting)
  m/<slug>/index.html                                  per-model page with its own meta tags
  sitemap.xml
and stamps ?v=<hash> onto image/icon URLs in index.html, model.html and 404.html.

Uses Pillow and resvg-py. It is safe to re-run; stale generated pages and images for models that
are no longer in models.json are removed.
"""
from __future__ import annotations

import hashlib
import html
import io
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from resvg_py import svg_to_bytes

if __package__:
    from .quick_site import build_quick_site
else:
    from quick_site import build_quick_site

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
ORIGIN = "https://bricks.superfun.games"
HOST = ORIGIN.removeprefix("https://")
SITE_NAME = "Bricks"
SHORT_NAME = "Bricks"
SITE_DESC = ("Buildable models made from real LEGO parts. Every part, connection and step "
             "checked by computer.")
GENERATED = "<!-- generated by tools/site_assets.py from model.html: edit model.html, not this file -->"

YELLOW = (254, 219, 5)
BLACK = (36, 34, 28)
WHITE = (255, 255, 255)
CREAM = (255, 253, 245)
MUTED = (111, 108, 99)
BG_LIGHT = "#fffdf5"
THEME = "#fffdf5"

MARK_SOURCE = SITE / "assets" / "brand" / "bricks.svg"
FONT = SITE / "assets" / "fonts" / "InterVariable.woff2"


# ---------------------------------------------------------------- helpers

def sha(path: Path, n: int = 10) -> str:
    return hashlib.sha1(path.read_bytes()).hexdigest()[:n]


def font(size: int, weight: int = 600) -> ImageFont.FreeTypeFont:
    f = ImageFont.truetype(str(FONT), size)
    try:
        values = []
        for axis in f.get_variation_axes():
            name = axis["name"].decode() if isinstance(axis["name"], bytes) else axis["name"]
            value = weight if name == "Weight" else min(size, 32) if name == "Optical size" else axis["default"]
            values.append(max(axis["minimum"], min(axis["maximum"], value)))
        f.set_variation_by_axes(values)
    except (OSError, ValueError):
        pass
    return f


def fmt_cm(mm: float) -> str:
    cm = mm / 10
    return f"{cm:.0f}" if cm >= 100 else f"{cm:.1f}".removesuffix(".0")


def lede(d: dict) -> str:
    """Same wording as ledeFor() in assets/js/model.js."""
    if d.get("description"):
        return d["description"]
    s = f"{d.get('pieces', d['parts']):,} real LEGO parts, about {fmt_cm((d.get('dims_mm') or [0, 0, 0])[1])} cm tall"
    extras = []
    if d.get("mechanism"):
        extras.append("a working mechanism")
    if d.get("lights"):
        extras.append("a built-in light" if len(d["lights"]) == 1 else "built-in lights")
    if extras:
        s += ", with " + " and ".join(extras)
    return s + ". Every part, connection and step checked by computer."


def best_render(renders: list[str]) -> str | None:
    for pat in (r"hero", r"three.?quarter"):
        for r in renders:
            if re.search(pat, r, re.I):
                return r
    return renders[0] if renders else None


def write_if_changed(path: Path, data: bytes | str) -> None:
    b = data.encode() if isinstance(data, str) else data
    if path.exists() and path.read_bytes() == b:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b)


def save_png(img: Image.Image, path: Path, **kw) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path, "PNG", optimize=True, **kw)


def rounded_mask(size: tuple[int, int], radius: int, scale: int = 4) -> Image.Image:
    w, h = size
    m = Image.new("L", (w * scale, h * scale), 0)
    ImageDraw.Draw(m).rounded_rectangle((0, 0, w * scale - 1, h * scale - 1), radius * scale, fill=255)
    return m.resize(size, Image.LANCZOS)


def wrap(text: str, f: ImageFont.FreeTypeFont, width: int) -> list[str]:
    words, lines, cur = text.split(), [], ""
    for w in words:
        t = f"{cur} {w}".strip()
        if f.getlength(t) <= width or not cur:
            cur = t
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


# ---------------------------------------------------------------- brand + icons

def brand_mark_svg(*, inline: bool = False, colour: str | None = None) -> str:
    """Use the supplied SVG as the single source of truth; never redraw its path."""
    svg = MARK_SOURCE.read_text().strip()
    if inline:
        svg = svg.replace("<svg ", '<svg class="brand-mark" aria-hidden="true" focusable="false" ', 1)
    if colour:
        svg = svg.replace('fill="currentColor"', f'fill="{colour}"', 1)
    return svg


def mark_image(size: int) -> Image.Image:
    """Render the exact mark with resvg, retaining its original viewBox."""
    png = svg_to_bytes(svg_string=brand_mark_svg(colour="#24221c"), width=size, height=size,
                       skip_system_fonts=True)
    return Image.open(io.BytesIO(png)).convert("RGBA")


def draw_mark(size: int, rounded: bool = True, content: float = 0.76) -> Image.Image:
    """Charcoal symbol on the yellow brand tile, supersampled for small favicons."""
    scale = 4
    side = size * scale
    img = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    if rounded:
        d.rounded_rectangle((0, 0, side - 1, side - 1), radius=side * 0.2, fill=YELLOW)
    else:
        d.rectangle((0, 0, side - 1, side - 1), fill=YELLOW)
    mark = mark_image(round(side * content))
    offset = ((side - mark.width) // 2, (side - mark.height) // 2)
    img.alpha_composite(mark, offset)
    return img.resize((size, size), Image.Resampling.LANCZOS)


def logo_square(size: int, content: float = 0.76) -> Image.Image:
    """Opaque app icon. Maskable variants reduce the mark into the central safe circle."""
    return draw_mark(size, rounded=False, content=content).convert("RGB")


def logo_compatibility(size: int = 1200) -> Image.Image:
    """Opaque cream artwork for existing booklet/video consumers of ROOT/logo.png.

    The video compositor keys the top-left colour: a light corner preserves both
    the charcoal mark and yellow tile, unlike transparent black image corners.
    """
    img = Image.new("RGB", (size, size), CREAM)
    tile_size = round(size * 0.5)
    tile = draw_mark(tile_size)
    img.paste(tile, ((size - tile_size) // 2, round(size * 0.14)), tile)
    d = ImageDraw.Draw(img)
    d.text((size / 2, size * 0.69), SITE_NAME, font=font(round(size * 0.15), 600),
           fill=BLACK, anchor="mt")
    return img


def brand_lockup(img: Image.Image, xy: tuple[int, int], tile_size: int = 48) -> None:
    """Draw the same mark and separate wordmark used by the site's header."""
    x, y = xy
    tile = draw_mark(tile_size)
    img.paste(tile, (x, y), tile)
    d = ImageDraw.Draw(img)
    d.text((x + tile_size + 13, y + tile_size / 2), SITE_NAME,
           font=font(round(tile_size * 0.72), 600), fill=BLACK, anchor="lm")


def favicon_svg() -> str:
    # Nest the original SVG to keep its supplied path and viewBox untouched.
    mark = brand_mark_svg(colour="#24221c").replace(
        "<svg ", '<svg x="8" y="8" width="48" height="48" ', 1)
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">\n'
            '<rect width="64" height="64" rx="13" fill="#fedb05"/>\n'
            + mark + '\n</svg>\n')


def build_brand() -> None:
    brand = SITE / "assets" / "brand"
    brand.mkdir(parents=True, exist_ok=True)
    compatibility = logo_compatibility()
    save_png(compatibility, ROOT / "logo.png")
    save_png(compatibility, SITE / "assets" / "logo.png")
    hdr = draw_mark(128)
    save_png(hdr, brand / "logo-header.png")
    hdr.save(brand / "logo-header.webp", "WEBP", quality=95, method=6)
    save_png(logo_square(600), brand / "logo-square.png")

    write_if_changed(SITE / "favicon.svg", favicon_svg())
    sizes = [16, 32, 48]
    draw_mark(48).save(SITE / "favicon.ico", format="ICO", sizes=[(s, s) for s in sizes])
    save_png(draw_mark(32), SITE / "favicon-32.png")
    save_png(logo_square(180), SITE / "apple-touch-icon.png")
    save_png(logo_square(192), SITE / "icon-192.png")
    save_png(logo_square(512), SITE / "icon-512.png")
    # The supplied silhouette at 68% fits inside the 80%-diameter safe circle.
    save_png(logo_square(192, 0.68), SITE / "icon-maskable-192.png")
    save_png(logo_square(512, 0.68), SITE / "icon-maskable-512.png")


def build_manifest() -> None:
    v = lambda name: f"/{name}?v={sha(SITE / name)}"          # noqa: E731
    manifest = {
        "name": SITE_NAME,
        "short_name": SHORT_NAME,
        "description": SITE_DESC,
        "id": "/",
        "start_url": "/",
        "scope": "/",
        "lang": "en",
        "dir": "ltr",
        "display": "standalone",
        "background_color": BG_LIGHT,
        "theme_color": THEME,
        "icons": [
            {"src": v("icon-192.png"), "sizes": "192x192", "type": "image/png", "purpose": "any"},
            {"src": v("icon-512.png"), "sizes": "512x512", "type": "image/png", "purpose": "any"},
            {"src": v("icon-maskable-192.png"), "sizes": "192x192", "type": "image/png", "purpose": "maskable"},
            {"src": v("icon-maskable-512.png"), "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
            {"src": v("favicon.svg"), "sizes": "any", "type": "image/svg+xml", "purpose": "any"},
        ],
    }
    write_if_changed(SITE / "site.webmanifest", json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------- OG images

def og_home() -> None:
    img = Image.new("RGB", (1200, 630), CREAM)
    brand_lockup(img, (64, 54))
    d = ImageDraw.Draw(img)
    headline = font(80, 600)
    d.text((64, 196), "For the love", font=headline, fill=BLACK, anchor="lt")
    d.text((64, 284), "of the build.", font=headline, fill=BLACK, anchor="lt")
    body = font(25, 400)
    d.text((68, 413), "Original models. Real LEGO parts.", font=body, fill=MUTED, anchor="lt")
    d.text((68, 451), "Discover a model. Make it yours.", font=body, fill=MUTED, anchor="lt")
    tile = draw_mark(334)
    img.paste(tile, (798, 160), tile)
    d.line((64, 548, 1136, 548), fill=(226, 221, 207), width=1)
    d.text((64, 573), HOST, font=font(20, 400), fill=MUTED, anchor="lt")
    save_png(img, SITE / "assets" / "og" / "home.png")


def crop_to_subject(pic: Image.Image, pad: float = 0.1) -> Image.Image:
    """Square crop around whatever differs from the studio background (estimated per row from
    the left and right edges), so the model fills the frame."""
    import numpy as np
    a = np.asarray(pic.convert("RGB")).astype(np.int16)
    edge = np.concatenate([a[:, :12], a[:, -12:]], axis=1)
    bg = np.median(edge, axis=1)[:, None, :]
    mask = np.abs(a - bg).sum(axis=2) > 36
    ys, xs = np.nonzero(mask)
    if len(xs) < 50:
        side = min(pic.size)
        return pic.crop(((pic.width - side) // 2, (pic.height - side) // 2, (pic.width + side) // 2, (pic.height + side) // 2))
    x0, x1, y0, y1 = xs.min(), xs.max(), ys.min(), ys.max()
    side = int(max(x1 - x0, y1 - y0) * (1 + 2 * pad))
    side = min(side, min(pic.size))
    cx, cy = (x0 + x1) // 2, (y0 + y1) // 2
    left = min(max(0, cx - side // 2), pic.width - side)
    top = min(max(0, cy - side // 2), pic.height - side)
    return pic.crop((left, top, left + side, top + side))


def og_model(m: dict, data: dict, slug_dir: Path) -> Path:
    img = Image.new("RGB", (1200, 630), CREAM)
    brand_lockup(img, (64, 54))
    renders = data.get("files", {}).get("renders") or []
    render = best_render(renders)
    frame = (520, 520)
    if render and (slug_dir / render).exists():
        with Image.open(slug_dir / render) as source:
            pic = crop_to_subject(source.convert("RGB"), pad=0.12)
        pic = pic.resize(frame, Image.Resampling.LANCZOS)
    else:
        pic = logo_square(frame[0], 0.6)
    img.paste(pic, (632, 55), rounded_mask(frame, 14))
    d = ImageDraw.Draw(img)
    name = data.get("name") or m.get("name") or m["slug"]
    size = 76
    while True:
        heading = font(size, 600)
        lines = wrap(name, heading, 500)
        if (len(lines) <= 2 and all(heading.getlength(line) <= 500 for line in lines)) or size <= 36:
            break
        size -= 2
    line_height = round(size * 1.12)
    y = 194
    for line in lines:
        d.text((62, y), line, font=heading, fill=BLACK, anchor="lt")
        y += line_height
    pieces = data.get("pieces", data.get("parts", 0))
    y = max(400, y + 35)
    d.text((66, y), f"{pieces:,} real LEGO parts", font=font(27, 500), fill=BLACK, anchor="lt")
    height = fmt_cm((data.get("dims_mm") or [0, 0, 0])[1])
    steps = len(data.get("steps") or [])
    detail = f"{height} cm tall" + (f"  ·  {steps:,} build steps" if steps else "")
    d.text((66, y + 44), detail, font=font(22, 400), fill=MUTED, anchor="lt")
    d.text((66, 554), HOST, font=font(20, 400), fill=MUTED, anchor="lt")
    out = SITE / "assets" / "og" / f"{m['slug']}.png"
    save_png(img, out)
    return out


# ---------------------------------------------------------------- per-model media

def model_media(slug: str, data: dict, slug_dir: Path) -> dict:
    files = {}
    for p in sorted(slug_dir.rglob("*")):
        if p.is_file() and not p.name.startswith("."):
            files[p.relative_to(slug_dir).as_posix()] = {"v": sha(p), "size": p.stat().st_size}
    images = {}
    out_dir = SITE / "assets" / "img" / slug
    wanted = set()
    renders = list(data.get("files", {}).get("renders") or [])
    renders += [r for c in data.get("companions") or [] for r in c.get("renders") or []]
    for r in renders:
        src = slug_dir / r
        if not src.exists():
            continue
        im = Image.open(src)
        im = im.convert("RGBA") if im.mode in ("RGBA", "LA", "P") else im.convert("RGB")
        # a companion's renders (companions/<slug>/...) keep their folder in the name
        stem = Path(r).stem if r.startswith("renders/") else r.rsplit(".", 1)[0].replace("/", "_")
        lg, sm = out_dir / f"{stem}.webp", out_dir / f"{stem}-480.webp"
        out_dir.mkdir(parents=True, exist_ok=True)
        key = files.get(r, {}).get("v", "")
        stamp = out_dir / f".{stem}.src"
        if not (lg.exists() and sm.exists() and stamp.exists() and stamp.read_text() == key):
            im.save(lg, "WEBP", quality=84, method=6)
            small = im.resize((480, round(480 * im.height / im.width)), Image.LANCZOS) if im.width > 480 else im
            small.save(sm, "WEBP", quality=82, method=6)
            stamp.write_text(key)
        wanted |= {lg.name, sm.name, stamp.name}
        images[r] = {"w": im.width, "h": im.height,
                     "lg": f"/assets/img/{slug}/{lg.name}?v={sha(lg)}",
                     "sm": f"/assets/img/{slug}/{sm.name}?v={sha(sm)}"}
    if out_dir.exists():
        for p in out_dir.iterdir():
            if p.name not in wanted:
                p.unlink()
    return {"files": files, "images": images}


# ---------------------------------------------------------------- pages

def attr(s: str) -> str:
    return html.escape(s, quote=False).replace('"', "&quot;")


def model_meta(m: dict, data: dict, og_v: str) -> str:
    slug = m["slug"]
    name = data.get("name") or m.get("name") or slug
    title = f"{name}: buildable LEGO model | {SITE_NAME}"
    og_title = f"{name}: buildable LEGO model"
    desc = lede(data)
    url = f"{ORIGIN}/m/{slug}/"
    og = f"{ORIGIN}/assets/og/{slug}.png?v={og_v}"
    image_alt = f"{name}, a model built from {data.get('pieces', data.get('parts', 0)):,} real LEGO parts, beside the Bricks logo"
    ld = {
        "@context": "https://schema.org",
        "@type": "CreativeWork",
        "name": name,
        "description": desc,
        "url": url,
        "image": og,
        "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": ORIGIN + "/"},
        "keywords": "LEGO, MOC, building instructions, parts list, " + name,
    }
    return "\n".join([
        f"<title>{html.escape(title, quote=False)}</title>",
        f'<meta name="description" content="{attr(desc)}">',
        '<meta name="robots" content="max-image-preview:large">',
        f'<link rel="canonical" href="{attr(url)}">',
        f'<meta property="og:site_name" content="{attr(SITE_NAME)}">',
        '<meta property="og:type" content="website">',
        '<meta property="og:locale" content="en_US">',
        f'<meta property="og:title" content="{attr(og_title)}">',
        f'<meta property="og:description" content="{attr(desc)}">',
        f'<meta property="og:url" content="{attr(url)}">',
        f'<meta property="og:image" content="{attr(og)}">',
        '<meta property="og:image:type" content="image/png">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{attr(image_alt)}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{attr(og_title)}">',
        f'<meta name="twitter:description" content="{attr(desc)}">',
        f'<meta name="twitter:image" content="{attr(og)}">',
        f'<meta name="twitter:image:alt" content="{attr(image_alt)}">',
        f'<script type="application/ld+json">{json.dumps(ld, ensure_ascii=False)}</script>',
    ])


def model_page(template: str, m: dict, data: dict, og_v: str, notice: str) -> str:
    slug = m["slug"]
    name = data.get("name") or slug
    page = re.sub(r"<!-- meta:start -->.*?<!-- meta:end -->",
                  lambda _: "<!-- meta:start -->\n" + model_meta(m, data, og_v) + "\n<!-- meta:end -->",
                  template, count=1, flags=re.S)
    page = page.replace('data-slug=""', f'data-slug="{attr(slug)}"', 1)
    page = re.sub(r'(<[^>]*data-fill="name"[^>]*>)[^<]*(<)', lambda mm: mm.group(1) + html.escape(name, quote=False) + mm.group(2), page)
    page = re.sub(r'(<[^>]*data-fill="description"[^>]*>)[^<]*(<)', lambda mm: mm.group(1) + html.escape(lede(data), quote=False) + mm.group(2), page)
    if notice:
        page = page.replace('<span id="model-notices"></span>', f'<span id="model-notices">{html.escape(notice, quote=False)}</span>', 1)
    return page.replace("<!doctype html>", "<!doctype html>\n" + GENERATED, 1)


STAMP_RE = re.compile(
    r'((?:href|src|srcset|content|poster)=")'
    rf'((?:{re.escape(ORIGIN)})?/(?!vendor/)[^"?#\s]+\.(?:png|webp|ico|svg|webmanifest|jpg|mp4))'
    r'(?:\?v=[0-9a-f]+)?(")'
)
BRAND_MARK_RE = re.compile(r'<!-- brand-mark:start -->.*?<!-- brand-mark:end -->', re.S)


def stamp(text: str) -> str:
    """Refresh inline brand marks and add content hashes to local image/icon URLs."""
    def rep(mm):
        url = mm.group(2)
        path = SITE / url.split(ORIGIN, 1)[-1].lstrip("/")
        if not path.is_file():
            return mm.group(0)
        return f"{mm.group(1)}{url}?v={sha(path)}{mm.group(3)}"
    text = BRAND_MARK_RE.sub(
        lambda _: "<!-- brand-mark:start -->" + brand_mark_svg(inline=True) + "<!-- brand-mark:end -->",
        text,
    )
    return STAMP_RE.sub(rep, text)


def sitemap(entries: list[tuple[str, str]]) -> str:
    rows = "\n".join(f"  <url><loc>{html.escape(u)}</loc><lastmod>{d}</lastmod></url>" for u, d in entries)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + rows + "\n</urlset>\n")


def day(path: Path) -> str:
    return datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).strftime("%Y-%m-%d")


# ---------------------------------------------------------------- main

def main() -> int:
    index_path = SITE / "models.json"
    if not index_path.exists():
        print("site/models.json not found: export a model first (python -m brickkit viewer <slug>)", file=sys.stderr)
        return 1
    models = json.loads(index_path.read_text()).get("models", [])
    conf_path = SITE / "site.json"
    conf = json.loads(conf_path.read_text()) if conf_path.exists() else {}
    notices = conf.get("notices", {})

    build_brand()
    build_manifest()
    og_home()

    template = (SITE / "model.html").read_text()
    quick = build_quick_site(SITE, ROOT / "models")
    media = {"models": {}}
    slugs = []
    regular_slugs = []
    entries = []
    for m in models:
        slug = m["slug"]
        slug_dir = SITE / "models" / slug
        mj = slug_dir / "model.json"
        if not mj.exists():
            print(f"  skip {slug}: {mj} missing", file=sys.stderr)
            continue
        data = json.loads(mj.read_text())
        slugs.append(slug)
        media["models"][slug] = model_media(slug, data, slug_dir)
        if data.get("collection") == "quick_bricks":
            print(f"  {slug}: QuickBricks assets")
            continue
        regular_slugs.append(slug)
        og = og_model(m, data, slug_dir)
        media["models"][slug]["og"] = f"/assets/og/{slug}.png?v={sha(og)}"
        notice = data.get("notice") or data.get("credits") or notices.get(slug, "")
        page = model_page(template, m, data, sha(og), notice)
        page_path = SITE / "m" / slug / "index.html"
        write_if_changed(page_path, stamp(page))
        entries.append((f"{ORIGIN}/m/{slug}/", max(day(mj), day(page_path))))
        print(f"  {slug}: page, og image, {len(media['models'][slug]['images'])} web images")

    # clean up generated output for models that are gone
    for d in (SITE / "m").glob("*/"):
        if d.name not in regular_slugs and (d / "index.html").exists() and GENERATED in (d / "index.html").read_text():
            shutil.rmtree(d)
    for p in (SITE / "assets" / "og").glob("*.png"):
        if p.stem != "home" and p.stem not in slugs:
            p.unlink()
    for d in (SITE / "assets" / "img").glob("*/"):
        if d.name not in slugs:
            shutil.rmtree(d)

    write_if_changed(SITE / "assets" / "media.json", json.dumps(media, indent=1) + "\n")
    home_day = max([day(SITE / "index.html")] + [e[1] for e in entries])
    extra = [(f"{ORIGIN}/videos/", max(home_day, day(SITE / "videos" / "index.html")))] \
        if (SITE / "videos" / "index.html").exists() else []
    quick_index = SITE / "quick" / "index.html"
    if quick_index.exists():
        extra.append((f"{ORIGIN}/quick/", day(quick_index)))
    for item in quick["models"]:
        page = SITE / "quick" / item["slug"] / "index.html"
        if page.exists():
            extra.append((ORIGIN + item["url"], day(page)))
    write_if_changed(SITE / "sitemap.xml", sitemap([(f"{ORIGIN}/", home_day)] + extra + entries))

    # the all-models showreel (brickkit sizzle -> showreel/), featured on the videos page
    for fn in ("sizzle.mp4", "sizzle_poster.jpg"):
        src, dst = ROOT / "showreel" / fn, SITE / "showreel" / fn
        if src.exists() and (not dst.exists() or sha(src) != sha(dst)):
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)

    for name in ("index.html", "model.html", "quick-model.html", "404.html", "videos/index.html", "quick/index.html"):
        p = SITE / name
        if p.exists():
            write_if_changed(p, stamp(p.read_text()))
    for page in (SITE / "quick").glob("*/index.html"):
        write_if_changed(page, stamp(page.read_text()))
    print(f"site assets written for {len(slugs)} model(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
